type: edu
files:
  - name: hypernews/__init__.py
    visible: true
    learner_created: false
  - name: hypernews/settings.py
    visible: true
    learner_created: false
  - name: hypernews/urls.py
    visible: true
    learner_created: false
  - name: hypernews/wsgi.py
    visible: true
    learner_created: false
  - name: news/migrations/__init__.py
    visible: true
    learner_created: false
  - name: news/__init__.py
    visible: true
    learner_created: false
  - name: news/admin.py
    visible: true
    learner_created: false
  - name: news/apps.py
    visible: true
    learner_created: false
  - name: news/models.py
    visible: true
    learner_created: false
  - name: news/tests.py
    visible: true
    learner_created: false
  - name: news/views.py
    visible: true
    learner_created: false
  - name: manage.py
    visible: true
    learner_created: false
  - name: test/__init__.py
    visible: false
    learner_created: false
  - name: test/base.py
    visible: false
    learner_created: false
  - name: test/tests.py
    visible: false
    learner_created: false
  - name: tests.py
    visible: false
    learner_created: false
  - name: news/templates/news/index.html
    visible: true
    learner_created: true
  - name: news/news.json
    visible: true
    learner_created: true
  - name: news/urls.py
    visible: true
    learner_created: true
  - name: db.sqlite3
    visible: true
    is_binary: true
    learner_created: true
  - name: news/migrations/0003_alter_news_options_alter_news_created.py
    visible: true
    learner_created: true
  - name: news/migrations/0001_initial.py
    visible: true
    learner_created: true
  - name: news/migrations/0004_alter_news_options.py
    visible: true
    learner_created: true
  - name: hypernews/news.json
    visible: true
    learner_created: true
  - name: news/templates/news/news_item_list.html
    visible: true
    learner_created: true
  - name: news/migrations/0002_news_created_news_link.py
    visible: true
    learner_created: true
  - name: news/templates/news/news_item_details.html
    visible: true
    learner_created: true
  - name: db.test.sqlite3
    visible: true
    learner_created: true
feedback_link: https://hyperskill.org/learn/step/9413#comment
status: Failed
feedback:
  message: |-
    Error in test #2

    [28/Apr/2024 00:25:19] "GET / HTTP/1.1" 200 265
    [28/Apr/2024 00:25:19] "GET / HTTP/1.1" 200 265
    Internal Server Error: /news/9234732/
    Traceback (most recent call last):
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
        return self.cursor.execute(sql, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
        return Database.Cursor.execute(self, query, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sqlite3.OperationalError: no such table: news_basemodel

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
        response = get_response(request)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
        return self.dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 142, in dispatch
        return handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/views/generic/list.py", line 154, in get
        self.object_list = self.get_queryset()
                           ^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/Documents/GitHub/HyperNews_Portal/HyperNews Portal/task/news/views.py", line 30, in get_queryset
        return News.objects.get(link=link).order_by('title')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 85, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/models/query.py", line 646, in get
        num = len(clone)
              ^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __len__
        self._fetch_all()
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1866, in _fetch_all
        self._result_cache = list(self._iterable_class(self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/models/query.py", line 87, in __iter__
        results = compiler.execute_sql(
                  ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
        cursor.execute(sql, params)
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in execute
        return super().execute(sql, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
        return self._execute_with_wrappers(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
        return executor(sql, params, many, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
        with self.db.wrap_database_errors:
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
        return self.cursor.execute(sql, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/paulwade/venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
        return Database.Cursor.execute(self, query, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    django.db.utils.OperationalError: no such table: news_basemodel
    [28/Apr/2024 00:25:19] "GET /news/9234732/ HTTP/1.1" 500 138275

    Please find below the output of your program during this failed test.

    ---

    stdout:
    Performing system checks...

    System check identified no issues (0 silenced).
    April 28, 2024 - 00:25:19
    Django version 4.1.1, using settings 'hypernews.settings'
    Starting development server at http://127.0.0.1:8001/
    Quit the server with CONTROL-C.

    stderr:
    [28/Apr/2024 00:25:19] "GET / HTTP/1.1" 200 265
    [28/Apr/2024 00:25:19] "GET / HTTP/1.1" 200 265
    Internal Server Error: /news/9234732/
    Traceback (most recent call last):
      File "venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
        return self.cursor.execute(sql, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
        return Database.Cursor.execute(self, query, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
        response = get_response(request)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
        return self.dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/views/generic/base.py", line 142, in dispatch
        return handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/views/generic/list.py", line 154, in get
        self.object_list = self.get_queryset()
                           ^^^^^^^^^^^^^^^^^^^
      File "Documents/GitHub/HyperNews_Portal/HyperNews Portal/task/news/views.py", line 30, in get_queryset
        return News.objects.get(link=link).order_by('title')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/models/manager.py", line 85, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/models/query.py", line 646, in get
        num = len(clone)
              ^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __len__
        self._fetch_all()
      File "venv/lib/python3.12/site-packages/django/db/models/query.py", line 1866, in _fetch_all
        self._result_cache = list(self._iterable_class(self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/models/query.py", line 87, in __iter__
        results = compiler.execute_sql(
                  ^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
        cursor.execute(sql, params)
      File "venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in execute
        return super().execute(sql, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
        return self._execute_with_wrappers(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
        return executor(sql, params, many, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
        with self.db.wrap_database_errors:
      File "venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
        return self.cursor.execute(sql, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
        return Database.Cursor.execute(self, query, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    django.db.utils.OperationalError: no such table: news_basemodel
    [28/Apr/2024 00:25:19] "GET /news/9234732/ HTTP/1.1" 500 138275
  time: "Sun, 28 Apr 2024 00:25:20 UTC"
record: -1
